color: null
fieldLayouts:
  45bb7801-7667-4559-893a-83bd668f7d8b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-18T08:19:44+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: afbdff45-217b-4839-b6fd-7c2b304c2bdb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-18T08:27:41+00:00'
            elementCondition: null
            fieldUid: c1614bab-5fdd-4eae-8e0b-f4eb393c25dd # Tekst
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e518077-e7d1-4fb4-919d-279e02fcceab
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fad5caf7-4109-4377-ac1c-7042307047e6
        userCondition: null
handle: activeer
hasTitleField: true
icon: null
name: Activeer
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
