color: null
fieldLayouts:
  1250eefd-e95b-4d37-b110-a937f3401f79:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-05T10:48:22+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 288c1b69-e4d8-4782-9a0c-0d27e0f5d19c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-05T10:51:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3935f25e-b3fe-4920-ba58-701ceaa8ee7e # Brand logo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6fab2b0c-d92e-4e5f-a47f-2bb5e6e35d23
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-05T10:51:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aa21d2ca-e34c-4497-a6fa-49b5a7cc7f58 # Title
            handle: null
            includeInCards: false
            instructions: null
            label: 'Discount title'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb15892c-ea65-47eb-bfc1-2f39bd3281d2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-05T10:51:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aa21d2ca-e34c-4497-a6fa-49b5a7cc7f58 # Title
            handle: textSingle2
            includeInCards: false
            instructions: null
            label: 'Discount code'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3874dfe8-2c36-4f4c-ae34-83b655fde3dc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-05T10:51:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6754b9ff-3f0c-41d6-914e-520590bd5d79 # LinkExtern
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f29d87b6-1ce9-4e7d-97da-fdc889f20abf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 517e5bd2-a2ee-4fca-827b-68c648b067c7
        userCondition: null
handle: discount
hasTitleField: true
icon: null
name: discount
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
