color: red
fieldLayouts:
  4f50c803-e346-4c16-a0b2-fe52e6a3a4c6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-03T16:20:36+00:00'
            elementCondition: null
            fieldUid: 40f481eb-0ec0-4642-ae8d-142718436d91 # Nummer
            handle: errorNum
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37730fd9-75ba-4854-aef5-6a9a62a590a5
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-24T10:28:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Titel
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f1cc6b9a-f539-4bd1-99e3-227351a0dede
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-24T10:28:35+00:00'
            elementCondition: null
            fieldUid: aa21d2ca-e34c-4497-a6fa-49b5a7cc7f58 # Title
            handle: null
            includeInCards: false
            instructions: null
            label: Subtitel
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eb5dbcf3-26c6-4e4a-8c7d-7d8e6bdc921e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-24T10:28:35+00:00'
            elementCondition: null
            fieldUid: c1614bab-5fdd-4eae-8e0b-f4eb393c25dd # Tekst
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d76d5711-1d9d-43d8-a058-fa1fa3084bfa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-24T10:28:35+00:00'
            elementCondition: null
            fieldUid: aa21d2ca-e34c-4497-a6fa-49b5a7cc7f58 # Title
            handle: textBtn
            includeInCards: false
            instructions: null
            label: 'Button tekst'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5cef3c3d-1501-4def-908b-276c14e8763a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4d309b43-059a-4e75-884c-1146af26b431
        userCondition: null
handle: errorContent
hasTitleField: true
icon: null
name: Error
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{errorNum}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
