color: null
fieldLayouts:
  df1c0b93-b050-46df-8dcb-0a82e19322cb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-18T08:18:13+00:00'
            elementCondition: null
            fieldUid: aa21d2ca-e34c-4497-a6fa-49b5a7cc7f58 # Title
            handle: altFirstName
            includeInCards: false
            instructions: null
            label: Voornaam
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 504a3b5d-4274-49ad-8528-f1acfc9640e2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-18T08:18:13+00:00'
            elementCondition: null
            fieldUid: aa21d2ca-e34c-4497-a6fa-49b5a7cc7f58 # Title
            handle: altLastName
            includeInCards: false
            instructions: null
            label: Familienaam
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a036833a-17e8-48b3-9e94-a7309c917539
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-18T08:18:13+00:00'
            elementCondition: null
            fieldUid: 3261931d-97c8-4b0e-a83a-6d9ac4dee153 # Birthday
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98c0cc75-98d9-4b0f-a747-c62dae9f611b
            userCondition: null
            warning: null
            width: 100
        name: Over
        uid: 8e882528-9d05-4508-bb00-f1cdae23b0be
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-18T08:18:13+00:00'
            elementCondition: null
            fieldUid: 93edcc59-32ca-4780-9d52-1d1fc486519a # Lid ouder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7509cc76-ba33-432b-aa35-ae8a99d8a7de
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-02T15:32:53+00:00'
            elementCondition: null
            fieldUid: 44a841e6-e727-4500-9e81-386090b011f6 # memberRate
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56019125-1bb5-4b91-ae8d-b79e7aba6045
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-07T12:56:15+00:00'
            elementCondition: null
            fieldUid: ab51ff2a-5865-41c8-897f-008e0b288a70 # Date
            handle: paymentDate
            includeInCards: false
            instructions: null
            label: Betalingsdatum
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d426d59d-5508-43a7-90a8-342fa1420189
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-08T09:45:30+00:00'
            elementCondition: null
            fieldUid: ab51ff2a-5865-41c8-897f-008e0b288a70 # Date
            handle: memberDueDate
            includeInCards: false
            instructions: null
            label: 'Vervaldatum lidmaatschap'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e04ecd2-f75e-4328-a33b-7805029438ac
            userCondition: null
            warning: null
            width: 100
        name: Lidmaatschap
        uid: 95b0fa11-e5aa-4784-bf45-98e943c08d33
        userCondition: null
handle: extraMember
hasTitleField: false
icon: user
name: 'Extra lid'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{object.altFirstName} {object.altLastName}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
