color: null
fieldLayouts:
  769f6f66-ea1a-4c80-866a-5a0fe4bfa10e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-13T09:48:25+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5c70d1a3-022b-4211-a14f-b52533371bcc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-13T09:48:25+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: be1c673f-0962-430c-8f77-56c215ba3ba8 # Form Select
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 504206e5-2288-49a4-924f-bf3a2ef5606a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-28T14:09:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: da3f503c-6206-4d5d-995a-375111712445 # Toevoegen als optie login
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca8d441f-be81-401d-ae6d-7f51a6e52bdb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-10T12:17:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: da3f503c-6206-4d5d-995a-375111712445 # Toevoegen als optie login
            handle: addOptions
            includeInCards: false
            instructions: null
            label: 'Opties toevoegen onder formulier'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8d2a39c-8d01-4461-b518-dd8f631e91fe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-08T08:21:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 72e433d6-096f-4419-aec5-dbd79c444034 # Switch
            handle: lostCard
            includeInCards: false
            instructions: null
            label: 'Kaart verloren formulier'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68d74942-b309-4ca5-9dab-df3dad4c0473
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-28T14:18:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aa21d2ca-e34c-4497-a6fa-49b5a7cc7f58 # Title
            handle: null
            includeInCards: false
            instructions: null
            label: Knop
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45c85ebf-f4b1-4cc7-b8fe-0eaf230baee3
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 745d363d-9830-4359-8749-48164353b9e2
        userCondition: null
handle: form
hasTitleField: true
icon: null
name: Formulier
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Aanvraag groep'
titleTranslationKeyFormat: null
titleTranslationMethod: site
