color: null
fieldLayouts:
  48a5a23b-2630-4e42-acbb-1d7978d23f8c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-06T16:20:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: eaf821d1-e9c8-4293-bbe8-0859c1ee0713
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-06T16:21:22+00:00'
            elementCondition: null
            fieldUid: c1614bab-5fdd-4eae-8e0b-f4eb393c25dd # Tekst
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3510f1c4-43a3-4d00-beb6-89a5aca2e008
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a2523d85-433f-4476-81ea-35abc30276b9
        userCondition: null
handle: notify
hasTitleField: true
icon: null
name: Notify
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
