color: null
fieldLayouts:
  ffc6d708-0818-476c-84d7-6d9c6fc7197a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-16T15:49:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Naam type'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c8ab94da-a715-4aea-b9b7-c43c66493ffc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-18T13:12:50+00:00'
            elementCondition: null
            fieldUid: 590f0cba-dbfa-4eda-882d-2fe3aac82a92 # Prijs
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99ca6b57-ba56-46fb-84f9-a2a17265b9e6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-02T16:01:54+00:00'
            elementCondition: null
            fieldUid: 2d35b4ae-62f0-4cb2-8a94-73ebdae1ef03 # Member type
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: caa94997-93b9-4c73-ad24-3e894fbc7fc4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-06T11:42:27+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 2d35b4ae-62f0-4cb2-8a94-73ebdae1ef03 # Member type
                  layoutElementUid: caa94997-93b9-4c73-ad24-3e894fbc7fc4
                  operator: in
                  uid: 51095439-6ad2-4a5d-b3e8-1faf45121c2d
                  values:
                    - individual
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 88eaa50e-c3b0-4b36-a2b9-11ef935830aa # min Leeftijd
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03e5e9e2-2fc6-4b13-b16a-a00ae13be4c9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-06T11:42:27+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 2d35b4ae-62f0-4cb2-8a94-73ebdae1ef03 # Member type
                  layoutElementUid: caa94997-93b9-4c73-ad24-3e894fbc7fc4
                  operator: in
                  uid: a62b90c4-bed0-4326-a71b-12776f227784
                  values:
                    - individual
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 8365fada-1ce2-4e0a-8a3f-f919c3c18208 # max Leeftijd
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ff715d1-7cf4-47fd-8ccb-8c14af90d9ef
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0a2ee47f-b505-4f90-9ec3-cb6df787a1ce
        userCondition: null
handle: rate
hasTitleField: true
icon: null
name: Tarief
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
