color: null
fieldLayouts:
  acdf35cf-5d46-4078-a33b-078483a010c7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-16T15:48:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Page title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 401f71fa-f894-4c84-bd84-02bb16a2fa31
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-17T10:36:35+00:00'
            elementCondition: null
            fieldUid: 44b08f22-3dad-45a3-a909-28dff91959b4
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f06c551e-0cfb-475e-8a96-becf7de4f800
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-17T10:35:46+00:00'
            elementCondition: null
            fieldUid: 87f9dfe3-9e75-489d-809f-7c3ad858c325
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a823dab-c01d-4532-bee7-fcd1bb55a50d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-17T10:35:46+00:00'
            elementCondition: null
            fieldUid: aa21d2ca-e34c-4497-a6fa-49b5a7cc7f58 # Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: caa4f096-3841-4588-b62e-8761fd648d05
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 05476d4d-c805-463e-9291-471ce1b2bae1
        userCondition: null
handle: register
hasTitleField: true
icon: null
name: Register
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
