allowPublicRegistration: true
deactivateByDefault: false
defaultGroup: 50a6f7cb-84e7-4d68-9aa9-3af2d9001e79 # Leden
photoSubpath: null
photoVolumeUid: null
require2fa: false
requireEmailVerification: true
validateOnPublicRegistration: true
