fromEmail: premium@hiflanders.be
fromName: 'Hi Flanders'
replyToEmail: null
template: email/email.twig
transportSettings:
  command: '/usr/local/bin/mailpit sendmail -t --smtp-addr 127.0.0.1:1025'
transportType: craft\mail\transportadapters\Sendmail
