tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2024-12-16T16:10:15+00:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\users\UsernameField
        uid: c5c6ddfc-13f6-4237-b332-f5e1460d023a
        userCondition: null
        warning: null
        width: 100
      -
        attribute: fullName
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2024-12-16T16:10:15+00:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: true
        required: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\users\FullNameField
        uid: cb06ff25-e418-4f03-bc9d-2e925c3a52ba
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2024-12-16T16:10:15+00:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\users\PhotoField
        uid: 7bbd049a-f60b-4b4a-a559-b819ef992254
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2024-12-17T11:13:13+00:00'
        elementCondition:
          class: craft\elements\conditions\users\UserCondition
          conditionRules:
            -
              class: craft\fields\conditions\OptionsFieldConditionRule
              fieldUid: 2d35b4ae-62f0-4cb2-8a94-73ebdae1ef03 # Member type
              layoutElementUid: 7e33f6e8-0b0e-400d-a437-2c89359c2d44
              operator: in
              uid: 749a2431-65ac-4770-aafd-339ae777afaf
              values:
                - individual
          elementType: craft\elements\User
          fieldContext: global
        fieldUid: aa21d2ca-e34c-4497-a6fa-49b5a7cc7f58 # Title
        handle: altFirstName
        includeInCards: false
        instructions: null
        label: Voornaam
        providesThumbs: false
        required: true
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: ce6736cd-f987-43c9-90cd-102a64414abe
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2024-12-17T11:13:55+00:00'
        elementCondition:
          class: craft\elements\conditions\users\UserCondition
          conditionRules:
            -
              class: craft\fields\conditions\OptionsFieldConditionRule
              fieldUid: 2d35b4ae-62f0-4cb2-8a94-73ebdae1ef03 # Member type
              layoutElementUid: 7e33f6e8-0b0e-400d-a437-2c89359c2d44
              operator: in
              uid: 9dac14e9-ea42-4ad9-998d-744b022b467c
              values:
                - individual
          elementType: craft\elements\User
          fieldContext: global
        fieldUid: aa21d2ca-e34c-4497-a6fa-49b5a7cc7f58 # Title
        handle: altLastName
        includeInCards: false
        instructions: null
        label: Achternaam
        providesThumbs: false
        required: true
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 6ac0afe4-fc85-4b39-831c-b08f6b50bf5c
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2024-12-18T14:41:34+00:00'
        elementCondition:
          class: craft\elements\conditions\users\UserCondition
          conditionRules:
            -
              class: craft\fields\conditions\OptionsFieldConditionRule
              fieldUid: 2d35b4ae-62f0-4cb2-8a94-73ebdae1ef03 # Member type
              layoutElementUid: 7e33f6e8-0b0e-400d-a437-2c89359c2d44
              operator: in
              uid: 560afdca-fe1a-4987-a728-e16d4abc3adf
              values:
                - group
          elementType: craft\elements\User
          fieldContext: global
        fieldUid: aa21d2ca-e34c-4497-a6fa-49b5a7cc7f58 # Title
        handle: organisation
        includeInCards: false
        instructions: null
        label: Organisatie
        providesThumbs: false
        required: true
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 40949dc7-a01d-4e59-b8ce-d0579608613d
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2024-12-16T16:12:37+00:00'
        elementCondition:
          class: craft\elements\conditions\users\UserCondition
          conditionRules:
            -
              class: craft\elements\conditions\users\GroupConditionRule
              operator: in
              uid: f8d21203-424b-421a-b995-54f0b71fa47f
              values:
                - 50a6f7cb-84e7-4d68-9aa9-3af2d9001e79 # Leden
          elementType: craft\elements\User
          fieldContext: global
        fieldUid: 3261931d-97c8-4b0e-a83a-6d9ac4dee153 # Birthday
        handle: null
        includeInCards: false
        instructions: null
        label: null
        providesThumbs: false
        required: true
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: f5acb2b0-a296-43ec-80b0-87cf4dda0141
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2024-12-19T15:20:13+00:00'
        elementCondition: null
        fieldUid: ab51ff2a-5865-41c8-897f-008e0b288a70 # Date
        handle: datePayment
        includeInCards: false
        instructions: null
        label: 'Datum betaling'
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: e7870079-b47e-440a-9075-ca69076ab9ef
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2025-01-02T13:13:00+00:00'
        elementCondition: null
        fieldUid: 5178f917-f380-440d-a326-c41e396ba39a # privacy policy
        handle: null
        includeInCards: false
        instructions: null
        label: null
        providesThumbs: false
        required: true
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: b830085b-1066-438a-bf29-a802e220b852
        userCondition: null
        warning: null
        width: 100
    name: Content
    uid: ae013ac9-d044-4fc1-85a9-cdfa5bb71919
    userCondition: null
  -
    elementCondition: null
    elements:
      -
        dateAdded: '2024-12-17T11:11:20+00:00'
        elementCondition: null
        fieldUid: aa21d2ca-e34c-4497-a6fa-49b5a7cc7f58 # Title
        handle: country
        includeInCards: false
        instructions: null
        label: 'Land '
        providesThumbs: false
        required: true
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 1e9c4549-9019-4bd9-8652-b90976b53a30
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2024-12-17T11:11:20+00:00'
        elementCondition: null
        fieldUid: aa21d2ca-e34c-4497-a6fa-49b5a7cc7f58 # Title
        handle: street
        includeInCards: false
        instructions: null
        label: Straat
        providesThumbs: false
        required: true
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: b283cd21-16ca-43bd-9495-48e0c7c630f3
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2024-12-17T11:58:15+00:00'
        elementCondition: null
        fieldUid: aa21d2ca-e34c-4497-a6fa-49b5a7cc7f58 # Title
        handle: streetNr
        includeInCards: false
        instructions: null
        label: Nummer
        providesThumbs: false
        required: true
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 811da2f6-b5e6-4fc3-b8d9-7f2f2e49a1c3
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2024-12-17T11:11:20+00:00'
        elementCondition: null
        fieldUid: aa21d2ca-e34c-4497-a6fa-49b5a7cc7f58 # Title
        handle: bus
        includeInCards: false
        instructions: null
        label: Bus
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: f9b78ac4-ee10-4870-94ff-d8e0670572d4
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2024-12-17T11:11:20+00:00'
        elementCondition: null
        fieldUid: aa21d2ca-e34c-4497-a6fa-49b5a7cc7f58 # Title
        handle: city
        includeInCards: false
        instructions: null
        label: Stad
        providesThumbs: false
        required: true
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: d1a0b663-1b4f-4c51-94ea-64a8f09f1470
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2024-12-17T11:58:15+00:00'
        elementCondition: null
        fieldUid: aa21d2ca-e34c-4497-a6fa-49b5a7cc7f58 # Title
        handle: postalCode
        includeInCards: false
        instructions: null
        label: Postcode
        providesThumbs: false
        required: true
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 2db58625-40da-47d1-9cc8-5d92692652c3
        userCondition: null
        warning: null
        width: 100
    name: Adres
    uid: 2789db09-a9ad-4779-886b-ffbc97ff25c1
    userCondition: null
  -
    elementCondition: null
    elements:
      -
        dateAdded: '2024-12-19T15:50:07+00:00'
        elementCondition:
          class: craft\elements\conditions\users\UserCondition
          conditionRules:
            -
              class: craft\fields\conditions\OptionsFieldConditionRule
              fieldUid: 2d35b4ae-62f0-4cb2-8a94-73ebdae1ef03 # Member type
              layoutElementUid: 7e33f6e8-0b0e-400d-a437-2c89359c2d44
              operator: in
              uid: ac976cbd-e673-4d83-b3db-e75e985c8afc
              values:
                - group
          elementType: craft\elements\User
          fieldContext: global
        fieldUid: aa21d2ca-e34c-4497-a6fa-49b5a7cc7f58 # Title
        handle: contactPerson
        includeInCards: false
        instructions: null
        label: Contactpersoon
        providesThumbs: false
        required: true
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: da184061-da82-42ee-a38c-41bd3934583f
        userCondition: null
        warning: null
        width: 100
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2024-12-16T16:10:15+00:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\users\EmailField
        uid: eab3f0ef-44dc-4b55-89fa-074791157097
        userCondition: null
        width: 100
      -
        dateAdded: '2024-12-19T15:52:15+00:00'
        elementCondition:
          class: craft\elements\conditions\users\UserCondition
          conditionRules:
            -
              class: craft\fields\conditions\OptionsFieldConditionRule
              fieldUid: 2d35b4ae-62f0-4cb2-8a94-73ebdae1ef03 # Member type
              layoutElementUid: 7e33f6e8-0b0e-400d-a437-2c89359c2d44
              operator: in
              uid: 29cebc08-e79b-45a7-8f69-eb0a28dbab89
              values:
                - group
          elementType: craft\elements\User
          fieldContext: global
        fieldUid: 2c2fb008-1e62-4ff3-906c-1018563ad030 # Tel
        handle: null
        includeInCards: false
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 34e53619-2edf-48ea-b674-bd48d0612fa8
        userCondition: null
        warning: null
        width: 100
    name: Contact
    uid: 29a009f6-fae3-4141-b690-3bfa8ef7d6eb
    userCondition: null
  -
    elementCondition: null
    elements:
      -
        dateAdded: '2025-01-02T14:39:49+00:00'
        elementCondition: null
        fieldUid: 2d35b4ae-62f0-4cb2-8a94-73ebdae1ef03 # Member type
        handle: null
        includeInCards: false
        instructions: null
        label: Type
        providesThumbs: false
        required: true
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 7e33f6e8-0b0e-400d-a437-2c89359c2d44
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2025-01-02T15:01:33+00:00'
        elementCondition: null
        fieldUid: 44a841e6-e727-4500-9e81-386090b011f6 # memberRate
        handle: null
        includeInCards: false
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: bfd5b7f9-52f4-4cb5-9dc6-fcb3f2202677
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2025-01-06T12:07:19+00:00'
        elementCondition: null
        fieldUid: aa21d2ca-e34c-4497-a6fa-49b5a7cc7f58 # Title
        handle: null
        includeInCards: false
        instructions: null
        label: test
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 93c7413e-8cc8-4e37-bce4-0c8f9261f146
        userCondition: null
        warning: null
        width: 100
    name: Lidmaatschap
    uid: 19cf21ec-6b32-476c-a140-abf35779079d
    userCondition: null
