altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  d2fe17b7-5532-4cde-bcbc-ac0cbda5c2a1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-08T13:39:21+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 034ea6b6-0c16-44de-a895-1c0782f6deb2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e005bb5c-0e1a-4412-9c5e-536c497b0497
        userCondition: null
fs: branding
handle: branding
name: Branding
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
