altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  b775d0e9-b2f6-4b08-8894-0eb673473d69:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-03T13:31:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 6003a276-d31d-47c8-86f0-62f561c2cd31
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 17b07d14-939c-489c-9a5e-6b7a9586d25a
        userCondition: null
fs: users
handle: users
name: Users
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: transforms
transformSubpath: $USERS_PATH_TRANSFORMS
