columnSuffix: null
handle: customStatus
instructions: null
name: 'Account status'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - New
        -
          - value
          - new
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Active
        -
          - value
          - active
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Renew
        -
          - value
          - renew
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Deactivated
        -
          - value
          - deactivated
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Oud actief'
        -
          - value
          - old
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Oud niet actief '
        -
          - value
          - oldRenew
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
