columnSuffix: null
handle: memberType
instructions: null
name: 'Member type'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Individueel
        -
          - value
          - individual
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Groep
        -
          - value
          - group
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Jeugdgroep
        -
          - value
          - groupYouth
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Werknemer
        -
          - value
          - employee
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Life member'
        -
          - value
          - life
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Lidkaart
        -
          - value
          - card
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
