columnSuffix: null
handle: privacyPolicy
instructions: null
name: 'privacy policy'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Geaccepteerd '
        -
          - value
          - accepted
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Checkboxes
