columnSuffix: null
handle: rateGroup
instructions: null
name: 'Tarief Groep'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Particulier
        -
          - value
          - individual
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Organisatie
        -
          - value
          - organisation
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
