columnSuffix: null
handle: requestPrintSend
instructions: null
name: 'Printaanvraag verstuurd'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
