columnSuffix: null
handle: tel
instructions: null
name: Tel
searchable: false
settings:
  maxLength: 255
  showLabelField: false
  showTargetField: false
  types:
    - tel
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
