columnSuffix: null
handle: textSimple
instructions: null
name: Tekst
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 77d8ae37-4c00-4972-aab9-94dd08c7f29c # SimpleText
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
