dateModified: 1743491248
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      defaultSort:
        - title
        - asc
      defaultViewMode: ''
      disabled: true
      key: singles
      tableAttributes:
        - status
        - link
      type: native
    -
      heading: 'Pagina''s'
      type: heading
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\elements\conditions\entries\SectionConditionRule
            operator: in
            uid: 462bbf2f-a4d3-4f5a-bccf-f8a550569ba6
            values:
              - 3a447095-116f-4a81-b2f7-43b6b4c1cf53
              - 7b5aa47e-5da6-461a-b6fc-a190a143d8d8 # Activeer email
              - e633efea-afa2-411f-9fc3-06d84f219d9b # Bedankt betaling
              - 4a63b33e-aa54-421b-b619-d4bc7f4888e7 # Home
              - ac77cfdb-37a0-4f35-9ca7-e353977a477d # Privacy policy
              - 22e6beae-01af-4451-b3d5-29bf90a51e80 # Reset wachtwoord
              - af17efa6-765d-4c48-99b6-d836a037abd9 # Succes registratie
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - id
        - asc
      defaultViewMode: ''
      key: 'custom:25a0c0a6-3dc5-41de-af42-23c27ec98692'
      label: 'Vaste pagina''s'
      tableAttributes: '-'
      type: custom
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:41bcf592-e8cf-43ee-8c4f-c83d185aee48' # Forms
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      key: 'section:1f19a7ba-f837-4abf-a622-317ac9fc02e5' # Errors
      type: native
    -
      heading: Collecties
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:1d223580-d398-4fc6-af8a-8a1e08933341' # Extra leden
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:5978149a-5b05-4ba3-95ff-72c6250597fe' # Tariefformules
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:3999db0f-4dbd-4784-8c12-a18c1f1ee8dd'
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      heading: Globals
      type: heading
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\elements\conditions\entries\SectionConditionRule
            operator: in
            uid: fa322204-aa99-498a-97a9-6014fbc0e0ec
            values:
              - e6b46871-c4a9-4c54-825a-0e4ff94ad028 # Branding
              - 4bf3f29c-fce9-401f-9b64-c00e46646ddc # Main website
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - id
        - asc
      defaultViewMode: ''
      key: 'custom:82a58549-8bec-49ba-9fb6-7a616719e62f'
      label: 'Bedrijfs gegevens'
      tableAttributes: '-'
      type: custom
    -
      heading: ''
      type: heading
email:
  fromEmail: lara@likeavirgin.be
  fromName: 'Hi Flanders'
  replyToEmail: null
  template: email/email.twig
  transportSettings:
    messageStream: ''
    token: $POSTMARK_API_KEY
  transportType: craftcms\postmark\Adapter
fs:
  branding:
    hasUrls: true
    name: Branding
    settings:
      path: $BRANDING_PATH
    type: craft\fs\Local
    url: $BRANDING_URL
  transforms:
    hasUrls: false
    name: Transforms
    settings:
      path: $TRANSFORMS_PATH
    type: craft\fs\Local
    url: null
  users:
    hasUrls: true
    name: Users
    settings:
      path: $USERS_PATH
    type: craft\fs\Local
    url: $USERS_URL
meta:
  __names__:
    1d0447d2-95ba-4d14-95bd-e1f51bb4dd4c: users # users
    1d223580-d398-4fc6-af8a-8a1e08933341: 'Extra leden' # Extra leden
    1f19a7ba-f837-4abf-a622-317ac9fc02e5: Errors # Errors
    2d35b4ae-62f0-4cb2-8a94-73ebdae1ef03: 'Member type' # Member type
    2e9932fc-c9cd-4c23-8ce1-ec6af9d45c81: 'Printaanvraag verstuurd' # Printaanvraag verstuurd
    3fa074c6-e343-4927-8f8e-9c209ddd6261: Betaalmethode # Betaalmethode
    3fab0971-effa-4787-a88b-2778ab3228d6: Notify # Notify
    4a63b33e-aa54-421b-b619-d4bc7f4888e7: Home # Home
    4bf3f29c-fce9-401f-9b64-c00e46646ddc: 'Main website' # Main website
    6a5cdbf8-b455-4bcd-a555-6a3fcad805f9: 'Hoofd website' # Hoofd website
    6a50b531-3d13-4fe9-95fa-16d3ce0c27d1: 'Gerigistreerd door ' # Gerigistreerd door 
    7b5aa47e-5da6-461a-b6fc-a190a143d8d8: 'Activeer email' # Activeer email
    7ca5fc34-985a-44f3-bc43-3f333f9457f3: CustomId # CustomId
    9a41348d-b717-4688-9000-767870baae38: New # New
    9b6463ce-f83c-4bd6-ad35-a79ab9818286: Users # Users
    9fa38d43-f532-46e6-a754-46a74621fb10: Branding # Branding
    21c22e0c-c629-4e07-9e19-a289ef81be37: Simple # Simple
    22e6beae-01af-4451-b3d5-29bf90a51e80: 'Reset wachtwoord' # Reset wachtwoord
    40f481eb-0ec0-4642-ae8d-142718436d91: Nummer # Nummer
    41bcf592-e8cf-43ee-8c4f-c83d185aee48: Forms # Forms
    44a841e6-e727-4500-9e81-386090b011f6: memberRate # memberRate
    50a6f7cb-84e7-4d68-9aa9-3af2d9001e79: Leden # Leden
    52ac72a5-0a6a-42ba-9e72-995b76380054: Logo # Logo
    72e433d6-096f-4419-aec5-dbd79c444034: Switch # Switch
    77d8ae37-4c00-4972-aab9-94dd08c7f29c: SimpleText # SimpleText
    88eaa50e-c3b0-4b36-a2b9-11ef935830aa: 'min Leeftijd' # min Leeftijd
    91c6a56d-e6ba-4757-a97d-293bf13c9115: Error # Error
    93edcc59-32ca-4780-9d52-1d1fc486519a: 'Lid ouder' # Lid ouder
    115f3616-1f1d-4238-bbd6-a35c5b4e8f28: 'Lidkaart type' # Lidkaart type
    359a39c5-8655-460f-a1b4-0c097ea0edb2: Ledensysteem # Ledensysteem
    590f0cba-dbfa-4eda-882d-2fe3aac82a92: Prijs # Prijs
    996e7f91-0447-4498-addc-bf91c17465f9: Taal # Taal
    5178f917-f380-440d-a326-c41e396ba39a: 'privacy policy' # privacy policy
    6754b9ff-3f0c-41d6-914e-520590bd5d79: LinkExtern # LinkExtern
    8365fada-1ce2-4e0a-8a3f-f919c3c18208: 'max Leeftijd' # max Leeftijd
    24815bbb-0421-4b52-9edb-4d6aa36625dc: 'Beheerder Super' # Beheerder Super
    80634baf-dc43-47ea-8528-2e72e4a53d61: Tarief # Tarief
    637277da-4bad-4da9-9b1a-059b6438cce0: 'Extra group' # Extra group
    3261931d-97c8-4b0e-a83a-6d9ac4dee153: Birthday # Birthday
    5978149a-5b05-4ba3-95ff-72c6250597fe: Tariefformules # Tariefformules
    a21d7477-05ca-43ea-ae84-fc44c3e16a70: 'Leden groep' # Leden groep
    aa21d2ca-e34c-4497-a6fa-49b5a7cc7f58: Title # Title
    ab51ff2a-5865-41c8-897f-008e0b288a70: Date # Date
    ac77cfdb-37a0-4f35-9ca7-e353977a477d: 'Privacy policy' # Privacy policy
    af17efa6-765d-4c48-99b6-d836a037abd9: 'Succes registratie' # Succes registratie
    b0a94379-cf08-4479-b96d-403ba096ee06: 'Print status' # Print status
    baf8aa85-b95e-4451-95dd-49dd26a47f81: 'Account status' # Account status
    bbdfff72-14f8-4e5d-b59e-12d5b73c9a17: Home # Home
    be1c673f-0962-430c-8f77-56c215ba3ba8: 'Form Select' # Form Select
    c095205f-0280-43c8-86ec-2705261bf6b9: Default # Default
    c573f0bd-29d4-4985-8cff-271a6ee231a2: Beheerder # Beheerder
    c1614bab-5fdd-4eae-8e0b-f4eb393c25dd: Tekst # Tekst
    c75441c9-96e6-40ff-ab4f-69ac95987e67: 'Promo codes ' # Promo codes 
    cd27b3c1-54f6-4e33-8a9f-02cba48208fa: 'Extra lid' # Extra lid
    d74da9d4-3821-46f5-8cf4-f7c4d12c04df: 'Ledensysteem fr' # Ledensysteem fr
    d89a41f8-5172-403a-a340-008b38d72227: 'Inschrijven voor nieuwsbrief' # Inschrijven voor nieuwsbrief
    d8718bb0-fa18-417d-92e8-3e7b464a8356: Formulier # Formulier
    d798439f-1df3-4d92-834c-7376e46fca7c: 'Privacy policy' # Privacy policy
    da3f503c-6206-4d5d-995a-375111712445: 'Toevoegen als optie login' # Toevoegen als optie login
    dad48958-bcb3-4253-9f7e-868f67fa27b0: 'Ledensysteem en' # Ledensysteem en
    db8cca95-36d6-43cd-977d-2c8d4ef17863: 'Contact Form' # Contact Form
    e6b46871-c4a9-4c54-825a-0e4ff94ad028: Branding # Branding
    e633efea-afa2-411f-9fc3-06d84f219d9b: 'Bedankt betaling' # Bedankt betaling
    f374ab43-38fa-4b2e-870f-70e2cccc4272: Branding # Branding
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 5.1.1
  formie:
    edition: standard
    enabled: true
    licenseKey: ZB80OHDNVOKXEFKE4AQEOXSU
    schemaVersion: 3.4.8
    settings:
      ajaxTimeout: 10
      alertEmails: null
      captchas:
        __assoc__:
          -
            - recaptcha
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Recaptcha
                -
                  - enabled
                  - '1'
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - recaptcha
                      -
                        - secretKey
                        - $RECAPTCHA_SECRET_KEY
                      -
                        - siteKey
                        - $RECAPTCHA_SITE_KEY
                      -
                        - type
                        - v3
                      -
                        - size
                        - normal
                      -
                        - theme
                        - light
                      -
                        - badge
                        - bottomright
                      -
                        - language
                        - en
                      -
                        - minScore
                        - 0.5
                      -
                        - scriptLoadingMethod
                        - asyncDefer
                      -
                        - enterpriseType
                        - score
          -
            - hcaptcha
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Hcaptcha
                -
                  - enabled
                  - '0'
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - hcaptcha
                      -
                        - size
                        - normal
                      -
                        - theme
                        - light
                      -
                        - language
                        - en
                      -
                        - minScore
                        - 0.5
                      -
                        - scriptLoadingMethod
                        - asyncDefer
          -
            - friendlyCaptcha
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\FriendlyCaptcha
                -
                  - enabled
                  - '0'
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - friendlyCaptcha
                      -
                        - language
                        - en
                      -
                        - startMode
                        - none
          -
            - turnstile
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Turnstile
                -
                  - enabled
                  - '0'
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - turnstile
                      -
                        - scriptLoadingMethod
                        - asyncDefer
                      -
                        - theme
                        - auto
                      -
                        - size
                        - normal
                      -
                        - appearance
                        - always
          -
            - duplicate
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Duplicate
                -
                  - enabled
                  - '0'
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - duplicate
          -
            - honeypot
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Honeypot
                -
                  - enabled
                  - '1'
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - honeypot
          -
            - javascript
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Javascript
                -
                  - enabled
                  - '1'
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - javascript
      defaultDateDisplayType: calendar
      defaultDateTime: null
      defaultDateValueOption: ''
      defaultEmailTemplate: ''
      defaultFileUploadVolume: ''
      defaultFormTemplate: ''
      defaultInstructionsPosition: verbb\formie\positions\AboveInput
      defaultLabelPosition: verbb\formie\positions\AboveInput
      defaultPage: forms
      emptyValuePlaceholder: 'No response.'
      enableBackSubmission: true
      enableCsrfValidationForGuests: true
      enableLargeFieldStorage: false
      enableUnloadWarning: true
      filterIntegrationMapping: true
      includeDraftElementUsage: false
      includeRevisionElementUsage: false
      maxIncompleteSubmissionAge: 30
      maxSentNotificationsAge: 30
      pdfPaperOrientation: portrait
      pdfPaperSize: letter
      pluginName: Formie
      queuePriority: null
      saveSpam: true
      sendEmailAlerts: false
      sentNotifications: true
      setOnlyCurrentPagePayload: false
      spamBehaviour: showSuccess
      spamBehaviourMessage: ''
      spamEmailNotifications: false
      spamKeywords: ''
      spamLimit: 500
      submissionsBehaviour: all
      useCssLayers: false
      useQueueForIntegrations: true
      useQueueForNotifications: true
      validateCustomTemplates: true
  postmark:
    edition: standard
    enabled: true
    schemaVersion: 2.0.1
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  translations-admin:
    edition: standard
    enabled: true
    licenseKey: RLKHCNGLTO2R9IUIW1CI5CWI
    schemaVersion: 1.1.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Hi flanders'
  retryDuration: null
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
