dateModified: 1734527570
elementSources:
  craft\elements\Entry:
    -
      key: '*'
      type: native
    -
      defaultSort:
        - title
        - asc
      defaultViewMode: ''
      disabled: true
      key: singles
      tableAttributes:
        - status
        - link
      type: native
    -
      heading: 'Pagina''s'
      type: heading
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\elements\conditions\entries\SectionConditionRule
            operator: in
            uid: 0d19fe3b-7362-4171-b78e-d28639e2b05b
            values:
              - 4a63b33e-aa54-421b-b619-d4bc7f4888e7 # Home
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - id
        - asc
      defaultViewMode: ''
      key: 'custom:afa208e6-7f3b-4035-ba9a-b601371ed7e2'
      label: Home
      tableAttributes: '-'
      type: custom
    -
      heading: Leden
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:1d223580-d398-4fc6-af8a-8a1e08933341' # Extra personen
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      heading: Formules
      type: heading
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:5978149a-5b05-4ba3-95ff-72c6250597fe' # Tariefformule
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - authors
        - link
      type: native
email:
  fromEmail: lara@likeavirgin.be
  fromName: users
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    00d6a85f-228e-4877-b53c-8725397c83d9: address # address
    1d0447d2-95ba-4d14-95bd-e1f51bb4dd4c: users # users
    1d223580-d398-4fc6-af8a-8a1e08933341: 'Extra personen' # Extra personen
    4a63b33e-aa54-421b-b619-d4bc7f4888e7: Home # Home
    7b5aa47e-5da6-461a-b6fc-a190a143d8d8: 'Activeer email' # Activeer email
    9a41348d-b717-4688-9000-767870baae38: New # New
    9ed2f6cf-f594-490a-b852-acaac49be4fc: Activeer # Activeer
    21c22e0c-c629-4e07-9e19-a289ef81be37: Simple # Simple
    50a6f7cb-84e7-4d68-9aa9-3af2d9001e79: Leden # Leden
    77d8ae37-4c00-4972-aab9-94dd08c7f29c: SimpleText # SimpleText
    93edcc59-32ca-4780-9d52-1d1fc486519a: 'Lid ouder' # Lid ouder
    359a39c5-8655-460f-a1b4-0c097ea0edb2: users # users
    590f0cba-dbfa-4eda-882d-2fe3aac82a92: Prijs # Prijs
    915a3019-dc60-443b-ab35-c471e10a8aed: Register # Register
    80634baf-dc43-47ea-8528-2e72e4a53d61: Tarief # Tarief
    3261931d-97c8-4b0e-a83a-6d9ac4dee153: Birthday # Birthday
    5978149a-5b05-4ba3-95ff-72c6250597fe: Tariefformule # Tariefformule
    15257075-d043-4ea1-a62e-1785e8ed7a5f: Tekst # Tekst
    aa21d2ca-e34c-4497-a6fa-49b5a7cc7f58: Title # Title
    bbdfff72-14f8-4e5d-b59e-12d5b73c9a17: Home # Home
    bcc31cfe-3e29-427b-89b2-8e771af767e9: Nummer # Nummer
    c573f0bd-29d4-4985-8cff-271a6ee231a2: 'Leden admin' # Leden admin
    c1614bab-5fdd-4eae-8e0b-f4eb393c25dd: Tekst # Tekst
    cd27b3c1-54f6-4e33-8a9f-02cba48208fa: 'Extra lid' # Extra lid
    db8cca95-36d6-43cd-977d-2c8d4ef17863: 'Contact Form' # Contact Form
    dbf7ddea-4516-47d3-a072-3707a9c6d1fd: Min # Min
    e18619bb-8aea-4d89-bacb-e80261037c94: Dashboard # Dashboard
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: ZB80OHDNVOKXEFKE4AQEOXSU
    schemaVersion: 3.4.7
  postmark:
    edition: standard
    enabled: true
    schemaVersion: 2.0.1
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: users
  schemaVersion: 5.5.0.0
  timeZone: America/Los_Angeles
