defaultPlacement: end
enableVersioning: true
entryTypes:
  - 9ed2f6cf-f594-490a-b852-acaac49be4fc # Activeer
handle: activate
maxAuthors: 1
name: 'Activeer email'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  359a39c5-8655-460f-a1b4-0c097ea0edb2: # users
    enabledByDefault: true
    hasUrls: true
    template: pages/activate.twig
    uriFormat: activeer-account
  d74da9d4-3821-46f5-8cf4-f7c4d12c04df: # users fr
    enabledByDefault: true
    hasUrls: true
    template: pages/activate.twig
    uriFormat: activer-compte
  dad48958-bcb3-4253-9f7e-868f67fa27b0: # users en
    enabledByDefault: true
    hasUrls: true
    template: pages/activate.twig
    uriFormat: activate-account
type: single
