defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: d8718bb0-fa18-417d-92e8-3e7b464a8356 # Formulier
handle: forms
maxAuthors: 1
name: Forms
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  359a39c5-8655-460f-a1b4-0c097ea0edb2: # users
    enabledByDefault: true
    hasUrls: true
    template: pages/form.twig
    uriFormat: '{slug}'
  d74da9d4-3821-46f5-8cf4-f7c4d12c04df: # users fr
    enabledByDefault: true
    hasUrls: true
    template: pages/form.twig
    uriFormat: '{slug}'
  dad48958-bcb3-4253-9f7e-868f67fa27b0: # users en
    enabledByDefault: true
    hasUrls: true
    template: pages/form.twig
    uriFormat: '{slug}'
type: channel
