defaultPlacement: end
enableVersioning: true
entryTypes:
  - bbdfff72-14f8-4e5d-b59e-12d5b73c9a17 # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  359a39c5-8655-460f-a1b4-0c097ea0edb2: # users
    enabledByDefault: true
    hasUrls: true
    template: pages/index.twig
    uriFormat: __home__
  d74da9d4-3821-46f5-8cf4-f7c4d12c04df: # users fr
    enabledByDefault: true
    hasUrls: true
    template: pages/index.twig
    uriFormat: __home__
  dad48958-bcb3-4253-9f7e-868f67fa27b0: # users en
    enabledByDefault: true
    hasUrls: true
    template: pages/index.twig
    uriFormat: __home__
type: single
