defaultPlacement: end
enableVersioning: true
entryTypes:
  - 0c156739-79ab-46b7-b364-734c05844fbe
handle: login
maxAuthors: 1
name: Login
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  359a39c5-8655-460f-a1b4-0c097ea0edb2: # users
    enabledByDefault: true
    hasUrls: true
    template: pages/login.twig
    uriFormat: login
type: single
