defaultPlacement: end
enableVersioning: true
entryTypes:
  - 6a5cdbf8-b455-4bcd-a555-6a3fcad805f9 # Hoofd website
handle: mainWebsite
maxAuthors: 1
name: 'Main website'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  359a39c5-8655-460f-a1b4-0c097ea0edb2: # users
    enabledByDefault: true
    hasUrls: true
    template: main-website/_entry.twig
    uriFormat: main-website
  d74da9d4-3821-46f5-8cf4-f7c4d12c04df: # users fr
    enabledByDefault: true
    hasUrls: true
    template: main-website/_entry.twig
    uriFormat: main-website
  dad48958-bcb3-4253-9f7e-868f67fa27b0: # users en
    enabledByDefault: true
    hasUrls: true
    template: main-website/_entry.twig
    uriFormat: main-website
type: single
