defaultPlacement: end
enableVersioning: true
entryTypes:
  - 3fab0971-effa-4787-a88b-2778ab3228d6 # Notify
handle: succesPayment
maxAuthors: 1
name: 'Bedankt betaling'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  359a39c5-8655-460f-a1b4-0c097ea0edb2: # users
    enabledByDefault: true
    hasUrls: true
    template: pages/notify.twig
    uriFormat: bedankt-betaling
  d74da9d4-3821-46f5-8cf4-f7c4d12c04df: # users fr
    enabledByDefault: true
    hasUrls: true
    template: pages/notify.twig
    uriFormat: bedankt-betaling
  dad48958-bcb3-4253-9f7e-868f67fa27b0: # users en
    enabledByDefault: true
    hasUrls: true
    template: pages/notify.twig
    uriFormat: bedankt-betaling
type: single
